import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { join, relative } from 'node:path'
import sharp from 'sharp'
import { z } from 'zod'
import type { CaptureProvider } from '@/capture/index'
import type { Clock } from '@/core/clock'

/**
 * Output of Claude Code's calibration analysis. Lists each mob species and
 * a bbox-in-frame to crop as a template. Saved as manifest-source.json
 * inside the calibration dir.
 */
export const ManifestSourceEntry = z.object({
  class: z.string(),
  variant: z.string().optional(),
  source_frame: z.string(), // e.g. "frames/0003.png"
  bbox_in_source: z.tuple([z.number(), z.number(), z.number(), z.number()]),
})
export const ManifestSource = z.object({
  templates: z.array(ManifestSourceEntry).min(1),
})
export type ManifestSource = z.infer<typeof ManifestSource>

export interface CalibrateOpts {
  capture: CaptureProvider
  clock: Clock
  outDir: string
  name: string
  frames?: number
  intervalMs?: number
}

/**
 * Capture N frames into data/calibrations/<name>/frames/, then write the
 * CALIBRATE.md prompt bundle the user feeds to Claude Code.
 */
export async function runCalibrate(opts: CalibrateOpts): Promise<{
  calibrationDir: string
  bundlePath: string
  framesCaptured: number
}> {
  const calibrationDir = join(opts.outDir, opts.name)
  const framesDir = join(calibrationDir, 'frames')
  mkdirSync(framesDir, { recursive: true })

  const total = opts.frames ?? 10
  const interval = opts.intervalMs ?? 1000
  const frameNames: string[] = []
  for (let i = 0; i < total; i++) {
    if (i > 0) await opts.clock.sleep(interval)
    const png = await opts.capture.captureScreen()
    const fname = `${String(i + 1).padStart(4, '0')}.png`
    // captureScreen returns raw RGB(A); we re-encode as PNG for portability.
    // Detect raw vs PNG by trying sharp on it directly — both work.
    const pngBuf = await sharp(png).png().toBuffer().catch(async () => {
      // Fallback: assume the buffer is already a raw RGBA matching the screen.
      // The underlying CaptureProvider impl shapes this; we just pass through.
      return png
    })
    writeFileSync(join(framesDir, fname), pngBuf)
    frameNames.push(`frames/${fname}`)
  }

  const bundlePath = writeBundle(calibrationDir, opts.name, frameNames)
  return { calibrationDir, bundlePath, framesCaptured: total }
}

function writeBundle(calibrationDir: string, name: string, frameNames: string[]): string {
  const cwd = process.cwd()
  const calRel = relative(cwd, calibrationDir)
  const sourceManifestRel = relative(cwd, join(calibrationDir, 'manifest-source.json'))
  const md = `# Calibration: ${name}

> Generated by maplestory.ai \`calibrate\`.
> Open this file in Claude Code and follow the instructions below.

## Your Role

You are inspecting Maplestory frames to identify the distinct enemy species
visible on the current map. The bot will use your output to build a template
library for runtime detection.

## Inputs

- Calibration dir: \`${calRel}/\`
- Frames (10 captures, 1 second apart):
${frameNames.map((f) => `  - \`${calRel}/${f}\``).join('\n')}

Read every frame as an image. Compare across frames to identify mob movement
and animation states.

## Your Task

For each distinct enemy species visible:

1. Pick **1–3 frames** that show the species in different visual states (idle,
   moving, attacking). Each frame becomes one template variant.
2. For each picked frame, give a **bounding box** in pixel coords \`[x, y, w, h]\`
   tightly enclosing the mob sprite. Avoid background and other mobs.
3. Use a stable class name (snake_case): \`mob_slime\`, \`mob_pig\`, etc.
   When unsure, use \`mob_a\`, \`mob_b\`, ...
4. Choose a \`variant\` label per crop: \`idle\`, \`move\`, \`attack\`, etc.

**Do NOT** include the player character, runes, portals, NPCs, or UI elements.
Only enemies the bot needs to detect for combat.

## Output

Write \`${sourceManifestRel}\` with this exact JSON shape:

\`\`\`json
{
  "templates": [
    {
      "class": "mob_slime",
      "variant": "idle",
      "source_frame": "frames/0003.png",
      "bbox_in_source": [420, 300, 80, 60]
    },
    {
      "class": "mob_slime",
      "variant": "attack",
      "source_frame": "frames/0007.png",
      "bbox_in_source": [430, 295, 84, 65]
    }
  ]
}
\`\`\`

## Next Step

After writing the JSON, the user runs:

\`\`\`bash
npm run dev -- crop-templates ${name}
\`\`\`

That command crops each \`bbox_in_source\` from the named frame and writes the
final \`data/templates/${name}/manifest.json\` + PNG crops.
`

  const bundlePath = join(calibrationDir, 'CALIBRATE.md')
  writeFileSync(bundlePath, md)
  return bundlePath
}

/**
 * Read manifest-source.json, crop each bbox from its source frame, and write
 * the canonical template manifest + PNG files into data/templates/<name>/.
 */
export async function cropTemplates(opts: {
  calibrationDir: string
  templatesDir: string
}): Promise<{
  templatesWritten: number
  manifestPath: string
}> {
  const sourcePath = join(opts.calibrationDir, 'manifest-source.json')
  if (!existsSync(sourcePath)) {
    throw new Error(`crop-templates: ${sourcePath} not found. Run Claude Code first.`)
  }
  const source = ManifestSource.parse(JSON.parse(readFileSync(sourcePath, 'utf8')))

  mkdirSync(opts.templatesDir, { recursive: true })
  const finalEntries: Array<{
    file: string
    class: string
    source_frame?: string
    bbox_in_source?: [number, number, number, number]
    variant?: string
  }> = []

  // Track per-class+variant counts so we can disambiguate filenames.
  const seen = new Map<string, number>()
  for (const t of source.templates) {
    const variant = t.variant ?? 'default'
    const key = `${t.class}-${variant}`
    const n = (seen.get(key) ?? 0) + 1
    seen.set(key, n)
    const file = n > 1 ? `${key}-${n}.png` : `${key}.png`

    const sourceFramePath = join(opts.calibrationDir, t.source_frame)
    if (!existsSync(sourceFramePath)) {
      throw new Error(`crop-templates: source frame ${sourceFramePath} not found`)
    }
    const [x, y, w, h] = t.bbox_in_source
    await sharp(sourceFramePath)
      .extract({ left: Math.round(x), top: Math.round(y), width: Math.round(w), height: Math.round(h) })
      .png()
      .toFile(join(opts.templatesDir, file))

    finalEntries.push({
      file,
      class: t.class,
      source_frame: t.source_frame,
      bbox_in_source: t.bbox_in_source,
      variant,
    })
  }

  const manifestPath = join(opts.templatesDir, 'manifest.json')
  writeFileSync(manifestPath, JSON.stringify({ templates: finalEntries }, null, 2))
  return { templatesWritten: finalEntries.length, manifestPath }
}
