import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { SYSTEM_PROMPT, buildUserPrompt } from './prompt'

export interface BundleOpts {
  recordingDir: string
  outRoutinePath: string
  framesEvery?: number
}

/**
 * Write a self-contained ANALYZE.md prompt file into the recording dir.
 * The user opens Claude Code in the project root and runs the
 * /analyze-recording slash command (or asks Claude Code to follow ANALYZE.md).
 *
 * No API key, no network call — Claude Code reads frames + logs via its Read
 * tool and writes the routine YAML via Write.
 */
export function writePromptBundle(opts: BundleOpts): {
  bundlePath: string
  framesSampled: number
} {
  const meta = JSON.parse(readFileSync(join(opts.recordingDir, 'meta.json'), 'utf8'))
  const inputs = readFileSync(join(opts.recordingDir, 'inputs.jsonl'), 'utf8')
  const vitals = readFileSync(join(opts.recordingDir, 'vitals.jsonl'), 'utf8')
  const frameNames = readdirSync(join(opts.recordingDir, 'frames')).sort()
  const every = opts.framesEvery ?? Math.max(1, Math.floor(frameNames.length / 40))
  const sampled = frameNames.filter((_, i) => i % every === 0).slice(0, 20)

  const userText = buildUserPrompt({
    framesSampled: sampled.length,
    resolution: meta.resolution,
    windowTitle: meta.windowTitle,
    inputsJsonl: inputs,
    vitalsJsonl: vitals,
  })

  const sampledRel = sampled.map((n) => relative(process.cwd(), join(opts.recordingDir, 'frames', n)))
  const inputsRel = relative(process.cwd(), join(opts.recordingDir, 'inputs.jsonl'))
  const vitalsRel = relative(process.cwd(), join(opts.recordingDir, 'vitals.jsonl'))
  const metaRel = relative(process.cwd(), join(opts.recordingDir, 'meta.json'))
  const outRel = relative(process.cwd(), opts.outRoutinePath)

  const md = `# Maplestory Recording Analysis

> Generated by maplestory.ai \`analyze\` command.
> Open this file in Claude Code and follow the instructions below.

## Your Role

${SYSTEM_PROMPT}

## Inputs to Read

- Meta: \`${metaRel}\`
- Inputs log (keystrokes): \`${inputsRel}\`
- Vitals log (HP/MP timeline): \`${vitalsRel}\`
- Sampled frames (${sampled.length} of ${frameNames.length}):
${sampledRel.map((p) => `  - \`${p}\``).join('\n')}

Use the Read tool to load every file above. Use multimodal viewing to inspect the frames.

## Output Path

Write the resulting YAML to: \`${outRel}\`

Mark \`unreviewed: true\` at the top level so the user must review before running.

## Task Specification

${userText}

## Validation Rules (post-write)

After writing the YAML, run:

\`\`\`bash
npm run dev -- run ${outRel} --mode dry-run
\`\`\`

If schema validation fails, read the error and rewrite the YAML.
`

  const bundlePath = join(opts.recordingDir, 'ANALYZE.md')
  writeFileSync(bundlePath, md)
  return { bundlePath, framesSampled: sampled.length }
}
